# Generated by Django 6.0.2 on 2026-02-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('organiser', 'Організатор'), ('admin', 'Адміністратор')], default='volunteer', max_length=20),
        ),
    ]
