# Generated by Django 6.0.2 on 2026-02-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0005_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_volunteers',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальна кількість волонтерів (0 - без обмежень)'),
        ),
    ]
