# Generated by Django 6.0.2 on 2026-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteer_app", "0013_eventtemplate_grouptemplate_hourstemplate_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE volunteer_app_project ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE volunteer_app_project DROP COLUMN IF EXISTS description;",
            state_operations=[
                migrations.AddField(
                    model_name="project",
                    name="description",
                    field=models.TextField(blank=True, default="", verbose_name="Опис"),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER TABLE volunteer_app_project ADD COLUMN IF NOT EXISTS location varchar(255) NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE volunteer_app_project DROP COLUMN IF EXISTS location;",
            state_operations=[
                migrations.AddField(
                    model_name="project",
                    name="location",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Місце проведення",
                    ),
                ),
            ],
        ),
    ]
