# Generated by Django 6.0.2 on 2026-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_app", "0018_userauthtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauthtoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
