from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from . import views

urlpatterns = [
    path("api/auth/login/", views.api_login, name="api_login"),
    path("api/projects/", views.api_projects, name="api_projects"),
    path(
        "api/projects/<int:project_id>/",
        views.api_project_detail,
        name="api_project_detail",
    ),
    path("api/projects/<int:project_id>/apply/", views.api_apply, name="api_apply"),
    path("api/applications/", views.api_my_applications, name="api_my_applications"),
    path(
        "api/projects/<int:project_id>/applications/",
        views.api_project_applications,
        name="api_project_applications",
    ),
    path("api/users/", views.api_users, name="api_users"),
    path("api/profile/", views.api_profile, name="api_profile"),
    path("api/profile/update/", views.api_profile_update, name="api_profile_update"),
    path("api/profile/password/", views.api_password_change, name="api_password_change"),
    path("api/goal/", views.api_goal, name="api_goal"),
    path("api/leaderboard/", views.api_leaderboard, name="api_leaderboard"),
    path("api/review/", views.api_review, name="api_review"),
    path("api/chat/users/", views.api_chat_users, name="api_chat_users"),
    path("api/chat/<str:username>/messages/", views.api_chat_messages, name="api_chat_messages"),
    path("api/chat/send/", views.api_chat_send, name="api_chat_send"),
    path("api/purchase/", views.api_purchase, name="api_purchase"),
    path("api/subscriptions/", views.api_subscriptions, name="api_subscriptions"),
    path("", views.landing, name="landing"),
    path("login/", views.login_view, name="login"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout_view, name="logout"),
    path("apply/<int:project_id>/", views.apply_project, name="apply_project"),
    path(
        "manage-request/<int:request_id>/<str:action>/",
        views.manage_request,
        name="manage_request",
    ),
    path(
        "report-volunteer/<int:request_id>/",
        views.report_volunteer,
        name="report_volunteer",
    ),
    path("toggle-star/<int:request_id>/", views.toggle_star, name="toggle_star"),
    path("user/<str:username>/", views.view_user_profile, name="view_user_profile"),
    path("create-project/", views.create_project, name="create_project"),
    path("project/<int:project_id>/", views.project_detail, name="project_detail"),
    path(
        "delete-project/<int:project_id>/", views.delete_project, name="delete_project"
    ),
    path("profile/", views.profile_view, name="profile"),
    path("settings/", views.settings_view, name="settings"),
    path("update-profile/", views.update_profile, name="update_profile"),
    path("update-password/", views.update_password, name="update_password"),
    path("import-students/", views.import_students, name="import_students"),
    path("edit-user/<str:username>/", views.edit_user, name="edit_user"),
    path("delete-user/<str:username>/", views.delete_user, name="delete_user"),
    path("bulk-delete-users/", views.bulk_delete_users, name="bulk_delete_users"),
    path("chat/", views.chat_view, name="chat"),
    path("chat/<str:username>/", views.chat_view, name="chat_with"),
    path("send-message/", views.send_message, name="send_message"),
    path("archive/", views.archive_view, name="archive"),
    path("templates/", views.templates_view, name="templates"),
    path("create-template/", views.create_template, name="create_template"),
    path("delete-template/", views.delete_template, name="delete_template"),
    path(
        "two-factor-password/",
        views.two_factor_password_change,
        name="two_factor_password",
    ),
    path("events/", views.events_page, name="events"),
    path("create-goal/", views.create_volunteer_goal, name="create_goal"),
    path("purchase/<str:plan_type>/", views.purchase_plan, name="purchase_plan"),
    path("analytics/", views.analytics_dashboard, name="analytics"),
    path("review/<int:request_id>/", views.leave_review, name="leave_review"),
    path("organizations/", views.organization_list, name="organization_list"),
    path("organizations/create/", views.create_organization, name="create_organization"),
    path("organizations/<slug:org_slug>/", views.organization_detail, name="organization_detail"),
]
